version: '3.9'
services:
  db:
    image: postgres:15
    container_name: auport_db
    environment:
      POSTGRES_DB: au_port
      POSTGRES_USER: au_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
